image: docker

services:
  - docker:dind

before_script:
  - export 
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} registry.gitlab.com


build:
   script:
     - docker pull registry.gitlab.com/korolkovdenis23/go_app_cicd:latest
     - docker build -t registry.gitlab.com/korolkovdenis23/go_app_cicd:${CI_COMMIT_SHORT_SHA} -t registry.gitlab.com/korolkovdenis23/go_app_cicd:latest . --cache-from  registry.gitlab.com/korolkovdenis23/go_app_cicd:latest
     - docker push registry.gitlab.com/korolkovdenis23/go_app_cicd:${CI_COMMIT_SHORT_SHA}    
     - docker push registry.gitlab.com/korolkovdenis23/go_app_cicd:latest

 

